name: Unit Test

on:
  push:
    branches: [ "main" ]
    paths:
      - src
      - test
  pull_request:
    branches: [ "main" ]
    paths:
      - src
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install Lua/LuaJIT
      # You may pin to the exact commit or the version.
      # uses: leafo/gh-actions-lua@d84e7d61946edb679210088bc1378c099fde51fe
      uses: leafo/gh-actions-lua@v9.1.0
      with:
        # The version of Lua to install, must be available on https://www.lua.org/ftp/ or http://luajit.org/download.html
        luaVersion: 5.1
        # Command line flags passed to make when building Lua
        #luaCompileFlags: # optional
        # Set to 'false' to skip restoring .lua from cache and always compile it
        #buildCache: # optional, default is true
        
    - name: Show Usage
      run: |
        cd test
        make
      
    - name: Run UnitTests
      run: |
        cd test
        make test
